# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env: 
  DOTNET_VERSION: "9.0"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore ProjectSetup.sln
    - name: Build
      run: dotnet build ProjectSetup.sln --no-restore
    - name: Test
      run: dotnet test ProjectSetup.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ProjectSetup.sln --Configuration Release --no-restore --no-build
